version: '2'

services:
  db:
    image: postgres:10.3
    ports:
      - 5431:5432
    volumes:
      - db:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  web:
    depends_on:
      - db
      - elasticsearch
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  db:
  elasticsearch:
