version: '2'

services:
  db:
    image: postgres:10.3
    ports:
      - 5431:5432
    volumes:
      - data:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  data:
