version: '2'

services:
  db:
    image: postgres:10.3
    volumes:
      - db-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data

  web:
    links:
      - db
      - elasticsearch
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env.example

volumes:
  db-data:
  es-data:
